---
# PostgreSQL
postgres_db: vtbhack_db
postgres_user: vtbhack

# Redis
redis_host: redis
redis_port: 6379

# Service ports
auth_port: 8080
bank_port: 8081
radar_port: 8082

# Service URLs
auth_url: "http://auth:8080"
bank_url: "http://bank:8081"
radar_url: "http://radar:8082"

# Registry
registry_url: ghcr.io
registry_prefix: petraart1/vtbhack
authService_version: "main-latest"
bankService_version: "main-latest"
radarService_version: "main-latest"

# Logging
logging_level_root: "INFO"
spring_profiles_active: "production"
