services:
  auth-db:
    image: 'postgres:16-alpine'

    container_name: auth-db

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - auth_db_data:/var/lib/postgresql/data:rw

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 3s
      retries: 3

  bank-db:
    image: 'postgres:16-alpine'

    container_name: bank-db

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - bank_db_data:/var/lib/postgresql/data:rw

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 3s
      retries: 3

  radar-db:
    image: 'postgres:16-alpine'

    container_name: radar-db

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5434:5432"

    volumes:
      - radar_db_data:/var/lib/postgresql/data:rw

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 3s
      retries: 3

  auth:
    container_name: auth

    build:
      context: ./backend/authService
      dockerfile: Dockerfile

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT: ${DB_PORT}
      AUTH_DB_CONTAINER_NAME: ${AUTH_DB_CONTAINER_NAME}
      JWT_SECRET: ${JWT_SECRET}

    ports:
      - "8080:8080"

    depends_on:
      auth-db:
        condition: service_healthy

  bank:
    container_name: bank

    build:
      context: ./backend/bankService
      dockerfile: Dockerfile

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT: ${DB_PORT}
      BANK_DB_CONTAINER_NAME: ${BANK_DB_CONTAINER_NAME}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_HOST: redis
      REDIS_PORT: 6379

    ports:
      - "8081:8080"

    depends_on:
      bank-db:
        condition: service_healthy
      redis:
        condition: service_healthy

  radar:
    container_name: radar

    build:
      context: ./backend/radarService
      dockerfile: Dockerfile

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT: ${DB_PORT}
      RADAR_DB_CONTAINER_NAME: ${RADAR_DB_CONTAINER_NAME}
      JWT_SECRET: ${JWT_SECRET}

    ports:
      - "8082:8080"

    depends_on:
      radar-db:
        condition: service_healthy

  redis:
    container_name: redis

    build:
      context: ./backend/_infrastructure/redis
      dockerfile: Dockerfile

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data:rw

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3

  nginx:
    container_name: nginx

    build:
      context: ./backend/_infrastructure/nginx
      dockerfile: Dockerfile

    ports:
      - "80:80"

    depends_on:
      - auth
      - bank
      - radar

  prometheus:
    container_name: prometheus
    build:
      context: ./backend/_infrastructure/prometheus
      dockerfile: Dockerfile

    restart: unless-stopped
    ports:
      - "9090:9090"
    networks:
      - monitoring_net

    depends_on:
      - auth
      - bank
      - radar

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - auth
      - bank
      - radar
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  auth_db_data:
  bank_db_data:
  radar_db_data:
  redis_data:

networks:
  monitoring_net:
    driver: bridge