object Version {
    const val composeUi = "1.6.0"
    const val composeMaterial3 = "1.2.0"
    const val lifecycleRuntime = "2.6.2"
    const val navigationCompose = "2.7.6"
    const val hilt = "2.48"
    const val room = "2.6.0"
    const val retrofit = "2.9.0"
    const val okhttp = "4.11.0"
    const val appauth = "0.11.1"
    const val sqlcipher = "4.5.4"
    const val securityCrypto = "1.1.0-alpha06"
    const val datastore = "1.1.0"
    const val work = "2.8.1"
    const val firebaseMessaging = "23.4.1"
    const val coil = "2.5.0"
    const val timber = "5.0.1"
    const val mockk = "1.13.7"
    const val junit = "4.13.2"
    const val junitExt = "1.1.5"
    const val espresso = "3.5.1"
    const val vicoCharts = "1.13.0"
}

object Deps {
    const val composeUi = "androidx.compose.ui:ui:${Version.composeUi}"
    const val composeMaterial3 = "androidx.compose.material3:material3:${Version.composeMaterial3}"
    const val composeAnimation = "androidx.compose.animation:animation:${Version.composeUi}"
    const val composeNavigation = "androidx.navigation:navigation-compose:${Version.navigationCompose}"
    const val lifecycleViewModel = "androidx.lifecycle:lifecycle-viewmodel-compose:${Version.lifecycleRuntime}"
    const val lifecycleRuntime = "androidx.lifecycle:lifecycle-runtime-compose:${Version.lifecycleRuntime}"
    const val hilt = "com.google.dagger:hilt-android:${Version.hilt}"
    const val hiltCompiler = "com.google.dagger:hilt-android-compiler:${Version.hilt}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Version.retrofit}"
    const val okhttp = "com.squareup.okhttp3:logging-interceptor:${Version.okhttp}"
    const val appauth = "net.openid:appauth:${Version.appauth}"
    const val room = "androidx.room:room-runtime:${Version.room}"
    const val roomCompiler = "androidx.room:room-compiler:${Version.room}"
    const val sqlcipher = "net.zetetic:android-database-sqlcipher:${Version.sqlcipher}"
    const val securityCrypto = "androidx.security:security-crypto:${Version.securityCrypto}"
    const val datastore = "androidx.datastore:datastore-preferences:${Version.datastore}"
    const val work = "androidx.work:work-runtime-ktx:${Version.work}"
    const val firebaseMessaging = "com.google.firebase:firebase-messaging:${Version.firebaseMessaging}"
    const val coilCompose = "io.coil-kt:coil-compose:${Version.coil}"
    const val timber = "com.jakewharton.timber:timber:${Version.timber}"
    const val vicoCharts = "com.patrykandpatrick.vico:compose-charts:${Version.vicoCharts}"
    // ТЕСТЫ
    const val junit = "junit:junit:${Version.junit}"
    const val mockk = "io.mockk:mockk:${Version.mockk}"
    const val junitExt = "androidx.test.ext:junit:${Version.junitExt}"
    const val espresso = "androidx.test.espresso:espresso-core:${Version.espresso}"
}