all:
  children:
    production:
      hosts:
        backend-prod:
          ansible_host: "{{ lookup('env', 'PRODUCTION_SERVER_IP') }}"
          ansible_user: deploy
          ansible_ssh_private_key_file: ~/.ssh/deploy_key
          ansible_python_interpreter: /usr/bin/python3
          deploy_environment: production