server:
  port: 8080

spring:
  application:
    name: authService

  datasource:
    url: jdbc:postgresql://${AUTH_DB_CONTAINER_NAME}:${DB_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update      # на dev удобно, на prod — миграции (Flyway/Liquibase)
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    show-sql: false

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID:Iv23li07pLEe2Kl7IzfP}
            client-secret: ${GITHUB_CLIENT_SECRET:e7d1bbf6be78950fb547984b0ed9f60a72fcdd48}
            scope: read:user,user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"


jwt:
  issuer: com.bank.auth
  secret: ${JWT_SECRET:34cf09cbe5571911e487cafcd49b72946a133fe881c3de75ab2d412f226ef06f}
  access-token-ttl: 15m
  refresh-token-ttl: 7d
  cookie:
    enabled: true
    secure: false   # на prod true (https)
    same-site: Lax
    domain: localhost
    path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

# Простой CORS (под фронт на http://localhost:3000)
app:
  cors:
    allowed-origins: "http://localhost:3000"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"

# OpenAPI (Swagger) конфигурация
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
  show-actuator: true
