global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    metrics_path: "/actuator/prometheus"

  - job_name: "auth"
    static_configs:
      - targets: ["auth:8080"]
    metrics_path: "/actuator/prometheus"

  - job_name: "bank"
    static_configs:
      - targets: [ "bank:8081" ]
    metrics_path: "/actuator/prometheus"

  - job_name: "radar"
    static_configs:
      - targets: [ "radar:8082" ]
    metrics_path: "/actuator/prometheus"